// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"
	"fengfengstudy/demo/user/rpc/internal/logic"
	"fengfengstudy/demo/user/rpc/internal/svc"
	user2 "fengfengstudy/demo/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user2.IdRequest) (*user2.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
